{
 "title": "AppState",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "Joomla" },
    { "expr": "mysql_up", "legendFormat": "DB" }
   ]
  },
  {
   "title": "Joomla",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Joomla http_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Slow queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "DB"
    }
   ]
  }
 ]
}