route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30s
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'telegram'
    - match:
        severity: warning
      receiver: 'web.hook'
receivers:
  - name: 'default'
    webhook_configs:
    - url: 'http://localhost:1010'
  - name: 'web.hook'
    webhook_configs:
    - url: 'https://api.telegram.org/bot***/sendMessage?chat_id=-1002062818733&text=LowMemory'
  - name: 'telegram'
    telegram_configs:
    - bot_token: "***"
      api_url: "https://api.telegram.org"
      chat_id: -1002062818733
      parse_mode: ""
      send_resolved: true
      message: "🚨 Alertmanager 🚨\nPANIC\n🔺 Alertname: {{ .GroupLabels.alertname}}\n🔺 Severity: {{ .CommonLabels.severity }}\n📌 {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
